package com.techbucketdivision.mystcraft.age.celestial;

import com.techbucketdivision.mystcraft.api.symbol.ColorGradient;
import net.minecraft.util.Mth;
import org.jspecify.annotations.Nullable;

import java.util.Random;

/**
 * Twinkling starfield (REQUIREMENTS §4.3.2 StarsTwinkle): {@link #LAYERS} layers x {@link #STARS_PER_LAYER} stars,
 * each layer with a random time offset; layer brightness
 * {@code clamp(1 - (cos(((t + offset) mod 100) / 100 * 2pi) * 2 + 0.25), 0, 1)}. Star positions are generated by the
 * renderer from {@link #layerSeed(int)} (derived from the symbol seed) so the mesh is reproducible on the client.
 */
public final class TwinkleStarfieldCelestial extends StarfieldCelestial {
    public static final int LAYERS = 10;
    public static final int STARS_PER_LAYER = 100;

    private final long[] offsets = new long[LAYERS];
    private final long[] layerSeeds = new long[LAYERS];

    public TwinkleStarfieldCelestial(long seed, @Nullable Float periodFactor, @Nullable Float angleDegrees, ColorGradient gradient) {
        super(seed, periodFactor, angleDegrees, gradient);
        // Continue the same seeded sequence the base constructor used (period, angle) as the original did.
        Random rand = new Random(seed);
        if (periodFactor == null) rand.nextDouble();
        if (angleDegrees == null) rand.nextDouble();
        for (int i = 0; i < LAYERS; i++) offsets[i] = rand.nextLong();
        for (int i = 0; i < LAYERS; i++) layerSeeds[i] = rand.nextLong();
    }

    @Override
    public Kind kind() {
        return Kind.STARS_TWINKLE;
    }

    public int layers() {
        return LAYERS;
    }

    public long layerSeed(int layer) {
        return layerSeeds[layer];
    }

    /** Brightness multiplier 0..1 of the given layer at the given age time. */
    public float layerBrightness(int layer, long time, float partialTick) {
        long t = (time + offsets[layer]) % 100L;
        if (t < 0) t += 100L;
        float f1 = (t + partialTick) / 100f;
        float f2 = 1.0f - (Mth.cos(f1 * Mth.PI * 2.0f) * 2.0f + 0.25f);
        return Mth.clamp(f2, 0f, 1f);
    }
}
