modLoader="javafml"
loaderVersion="[3,)"
license="${mod_license}"
issueTrackerURL="https://github.com/TheDruidsKeeper/mystcraft-reborn/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/TheDruidsKeeper/mystcraft-reborn"
logoFile="mystcraft_logo.png"
credits="Original Mystcraft by XCompWiz (LGPL-3.0). Dynamic dimension technique after Commoble's Infiniverse (MIT)."
authors="${mod_authors}"
description='''${mod_description}'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[features.${mod_id}]
javaVersion="[25,)"
